"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
import Navbar from "@/components/Navbar";
import { AppWrapper } from "@/context";
import AppContext from "@/context";

export default function RootLayout({ children }) {
  const [find, setFind] = useState("");
  return (
    <html lang="en">
      <AppContext.Provider value={{ find, setFind }}>
        <body>
          <Navbar />
          {children}
        </body>
      </AppContext.Provider>
    </html>
  );
}
